# Generated by Django 3.2.6 on 2021-09-25 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20210921_2220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comentário'},
        ),
    ]
