# Generated by Django 3.2.6 on 2021-10-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='id_partner',
            field=models.CharField(default='', max_length=500, verbose_name='id_partner'),
        ),
    ]
