# Generated by Django 3.2.6 on 2021-10-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_merge_0004_delete_comment_0005_store_style_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/category/image'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/subcategory/image'),
        ),
    ]
