# Generated by Django 3.2.6 on 2021-10-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_subcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='banner',
            field=models.FileField(blank=True, null=True, upload_to='img/category/banner'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='img/category/image'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='img/subcategory/image'),
        ),
    ]
