# Generated by Django 3.2.6 on 2021-10-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_store_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='primary_color',
            field=models.CharField(default='', max_length=50, verbose_name='primary_color'),
        ),
    ]
