# Generated by Django 3.2.6 on 2021-10-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_store_primary_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='primary_color',
            field=models.CharField(default='#ffffff', max_length=50, verbose_name='primary_color'),
        ),
    ]
