# Generated by Django 3.2.6 on 2021-10-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_alter_store_primary_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
