# Generated by Django 3.2.6 on 2021-09-17 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('cpf', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título do Produto')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço do Produto')),
                ('relevant', models.BooleanField(default=False)),
                ('long_url', models.URLField(blank=True)),
                ('payments', models.CharField(choices=[('À VISTA', 'À vista'), ('1', '1x'), ('2', '2x')], max_length=35, verbose_name='Forma de Pagamento')),
                ('short_url', models.CharField(blank=True, max_length=40)),
                ('coupon', models.CharField(blank=True, max_length=40, verbose_name='Cupom')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, upload_to='img/products/%Y/%m')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.store')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Produto',
            },
        ),
    ]
