# Generated by Django 3.2.6 on 2021-09-27 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_comment_options'),
        ('product', '0004_alter_product_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='payments',
        ),
        migrations.AddField(
            model_name='product',
            name='form_payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.form_payment'),
        ),
        migrations.AddField(
            model_name='product',
            name='freight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.freight'),
        ),
        migrations.AddField(
            model_name='product',
            name='warning',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='management.warning'),
        ),
    ]
