# Generated by Django 3.2.6 on 2021-10-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210927_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='long_url',
            field=models.URLField(),
        ),
    ]
