# Generated by Django 3.2.6 on 2021-10-03 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_comment_options'),
        ('product', '0008_product_image_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='warning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.warning'),
        ),
    ]
