# Generated by Django 3.2.6 on 2021-10-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_report_problem_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_problem',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
