# Generated by Django 3.2.6 on 2021-10-13 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_report_problem_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report_problem',
            name='user',
        ),
    ]
