# Generated by Django 3.2.6 on 2021-10-13 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_remove_report_problem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
    ]
