# Generated by Django 3.2.6 on 2021-10-13 16:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20211013_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, max_length=255, unique=True),
        ),
    ]
