# Generated by Django 3.2.6 on 2021-10-13 18:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid1, max_length=255, unique=True),
        ),
    ]
