# Generated by Django 3.2.6 on 2021-10-13 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_remove_comment_date'),
        ('product', '0021_alter_product_slug'),
    ]

    operations = [
    ]
