# Generated by Django 3.2.6 on 2021-10-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_merge_20211013_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
