# Generated by Django 3.2.6 on 2021-10-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_alter_product_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Ativo'), ('INACTIVE', 'Inativo'), ('PENDING', 'Pendente'), ('EXPIRED', 'Expirado')], default='PENDING', max_length=20, verbose_name='status'),
        ),
    ]
