# Generated by Django 3.2.6 on 2021-10-21 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_auto_20211020_1401'),
        ('product', '0029_comment_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_store', to='management.store'),
            preserve_default=False,
        ),
    ]
