# Generated by Django 3.2.6 on 2021-10-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_auto_20211028_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='facebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='instagram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='telegram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='whatsapp',
            field=models.BooleanField(default=False),
        ),
    ]
