# Generated by Django 3.2.6 on 2021-10-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_auto_20211029_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='facebook',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='instagram',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='telegram',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='whatsapp',
            field=models.BooleanField(default=True),
        ),
    ]
