# Generated by Django 3.2.6 on 2021-11-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_auto_20211106_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='long_url',
            field=models.URLField(max_length=400),
        ),
    ]
