# Generated by Django 3.2.6 on 2021-10-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupWhatsapp',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('link_convite', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('type_social', models.CharField(choices=[('W', 'WhatsApp'), ('I', 'Instagram'), ('T', 'Telegram')], max_length=20)),
            ],
        ),
    ]
