# Generated by Django 3.2.6 on 2021-11-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupswhats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Margin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('num1', models.IntegerField()),
                ('num2', models.IntegerField()),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Margen',
            },
        ),
        migrations.AlterModelOptions(
            name='groupwhatsapp',
            options={'verbose_name': 'Grupos WhatsApp'},
        ),
    ]
