# Generated by Django 3.2.6 on 2021-11-19 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupswhats', '0004_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Mensagen'},
        ),
    ]
