# Generated by Django 3.2.6 on 2021-09-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.FileField(null=True, upload_to='imgUsers/%Y/%m/%d'),
        ),
    ]
