# Generated by Django 3.2.6 on 2021-10-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(db_index=True, default='Usuário sem nome', max_length=255),
            preserve_default=False,
        ),
    ]
